f=open("newfile.txt","w")
f.write("hellow world \n")
f.write("this is damoder speaking \n")
f.write("from idukki  \n")
f.write("munnar \n")
f.write("blababallbabalbablbalbalbababbaaaa\n")
f.close()
str=f.read()
f=open("newfile.txt","w")
print("read strings:",str)
f.close()
