f=open("text.txt","w")
f.write("my first file\n")
print("file",f.name,"closed")
f.write("hellow world \n")
f.write("this is sukumaran speaking \n")
f.write("hhihihihihihiihh \n")
f.close()
f=open("text.txt",'r')
str=f.read()
print("read strings:",str)
f.close()
